-- =========================================================
--  Migración: catálogo de MENÚ Contab. / RRHH (BD master)
--  Posición = índice 1-based dentro de USUARIOEMPRESA.MENU
--  Módulo:  1 = Contabilidad, 2 = RRHH
-- =========================================================

-- [master]
CREATE TABLE TMP$USUARIO_MENU_MASTER (
  POSICION INTEGER     NOT NULL,
  TITULO   VARCHAR(60) NOT NULL,
  MODULO   INTEGER     NOT NULL,
  CONSTRAINT PK_TMP_MENU_MASTER PRIMARY KEY (POSICION)
);

-- Contabilidad (12)
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES ( 1, 'Diario',                  1);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES ( 2, 'Mayor',                   1);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES ( 3, 'Libro Fiscal',            1);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES ( 4, 'Inventario Activo Fijo',  1);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES ( 5, 'Procesos',                1);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES ( 6, 'Sumas y Saldos',          1);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES ( 7, 'Estados de Resultados',   1);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES ( 8, 'General',                 1);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES ( 9, 'Impositivo',              1);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES (10, 'Plan de Cuentas',         1);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES (11, 'Definiciones',            1);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES (12, 'Propiedades',             1);

-- RRHH (7)
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES (13, 'Liquidación de Salarios', 2);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES (14, 'Movimientos',             2);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES (15, 'Control de Acceso',       2);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES (16, 'Planilla Seguro Social',  2);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES (17, 'Libro Laboral',           2);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES (18, 'Legajo del Personal',     2);
INSERT INTO TMP$USUARIO_MENU_MASTER (POSICION, TITULO, MODULO) VALUES (19, 'Propiedades',             2);
